// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The set of pre-bundled POS audio assets.
enum PosSound: Int {
  case scannerBeep = 0
  case warningBeep = 1
  case doubleWarningBeep = 2
  case kaching = 3
}

/// The set of native haptic feedback types for POS interactions.
enum PosHaptic: Int {
  case success = 0
  case warning = 1
  case error = 2
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PosSound(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PosHaptic(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PosSound {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PosHaptic {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API for ultra-low-latency native haptic and audio feedback.
///
/// All communication flows from Flutter → Native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HapticsAndAudioApi {
  /// Pre-loads all audio assets into native RAM and prepares
  /// the haptic engine. Must complete before any playback calls.
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  /// Instantly plays the specified pre-loaded audio asset.
  func playSound(sound: PosSound) throws
  /// Instantly triggers the specified native haptic pattern.
  func playHaptic(haptic: PosHaptic) throws
  /// Releases all native audio resources and haptic generators
  /// from memory. Call when the scanner is disposed.
  func release() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HapticsAndAudioApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HapticsAndAudioApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HapticsAndAudioApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Pre-loads all audio assets into native RAM and prepares
    /// the haptic engine. Must complete before any playback calls.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Instantly plays the specified pre-loaded audio asset.
    let playSoundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.playSound\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playSoundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let soundArg = args[0] as! PosSound
        do {
          try api.playSound(sound: soundArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playSoundChannel.setMessageHandler(nil)
    }
    /// Instantly triggers the specified native haptic pattern.
    let playHapticChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.playHaptic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playHapticChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hapticArg = args[0] as! PosHaptic
        do {
          try api.playHaptic(haptic: hapticArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playHapticChannel.setMessageHandler(nil)
    }
    /// Releases all native audio resources and haptic generators
    /// from memory. Call when the scanner is disposed.
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { _, reply in
        do {
          try api.release()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
  }
}
