name: native_haptics_and_audio
description: A high-performance Flutter plugin delivering ultra-low latency audio and haptic feedback for POS barcode scanners. By bypassing heavy audio packages and leveraging native hardware APIs with pre-bundled uncompressed sounds, it guarantees instant, zero-lag physical and auditory responses on Android and iOS.
version: 1.0.0
homepage: https://github.com/andresmontaniv/native_haptics_and_audio
repository: https://github.com/andresmontaniv/native_haptics_and_audio
issue_tracker: https://github.com/andresmontaniv/native_haptics_and_audio/issues

topics:
  - haptics
  - audio
  - pos
  - barcode-scanner
  - native

environment:
  sdk: ^3.11.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      android:
        package: com.andresmontano.native_haptics_and_audio
        pluginClass: NativeHapticsAndAudioPlugin
      ios:
        pluginClass: NativeHapticsAndAudioPlugin

