name: native_haptics_and_audio
description: Ultra-low latency native haptic and audio feedback designed specifically for high-speed POS barcode scanners on iOS and Android.
version: 1.0.1
homepage: https://github.com/andresmontaniv/native_haptics_and_audio
repository: https://github.com/andresmontaniv/native_haptics_and_audio
issue_tracker: https://github.com/andresmontaniv/native_haptics_and_audio/issues

topics:
  - haptics
  - audio
  - pos
  - barcode-scanner
  - native

environment:
  sdk: ^3.11.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      android:
        package: com.andresmontano.native_haptics_and_audio
        pluginClass: NativeHapticsAndAudioPlugin
      ios:
        pluginClass: NativeHapticsAndAudioPlugin

