// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.andresmontano.native_haptics_and_audio

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** The set of pre-bundled POS audio assets. */
enum class PosSound(val raw: Int) {
  /** Standard checkout scanner confirmation beep. */
  SCANNER_BEEP(0),
  /** Single warning tone for attention-needed events. */
  WARNING_BEEP(1),
  /** Urgent double-beep for errors or duplicate scans. */
  DOUBLE_WARNING_BEEP(2),
  /** Cash register "ka-ching" for completed transactions. */
  KACHING(3);

  companion object {
    fun ofRaw(raw: Int): PosSound? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The set of native haptic feedback types for POS interactions. */
enum class PosHaptic(val raw: Int) {
  /** Crisp, short mechanical tick — confirms a successful scan. */
  SUCCESS(0),
  /** Medium-intensity pulse — signals a non-critical warning. */
  WARNING(1),
  /** Heavy double-buzz — signals an error or rejected scan. */
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): PosHaptic? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PosSound.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PosHaptic.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PosSound -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PosHaptic -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for ultra-low-latency native haptic and audio feedback.
 *
 * All communication flows from Flutter → Native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HapticsAndAudioApi {
  /**
   * Pre-loads all audio assets into native RAM and prepares
   * the haptic engine. Must complete before any playback calls.
   */
  fun initialize(callback: (Result<Unit>) -> Unit)
  /** Instantly plays the specified pre-loaded audio asset. */
  fun playSound(sound: PosSound)
  /** Instantly triggers the specified native haptic pattern. */
  fun playHaptic(haptic: PosHaptic)
  /**
   * Releases all native audio resources and haptic generators
   * from memory. Call when the scanner is disposed.
   */
  fun release()

  companion object {
    /** The codec used by HapticsAndAudioApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HapticsAndAudioApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HapticsAndAudioApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.playSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val soundArg = args[0] as PosSound
            val wrapped: List<Any?> = try {
              api.playSound(soundArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.playHaptic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hapticArg = args[0] as PosHaptic
            val wrapped: List<Any?> = try {
              api.playHaptic(hapticArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.native_haptics_and_audio.HapticsAndAudioApi.release$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.release()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
